import type { DocsAppConfig } from "@prismio/docs-core";

export const docsConfig: DocsAppConfig = {
    site: {
        name: "Prismio Developers",
        shortName: "Prismio",
        description: "Implementation reference for the self-hosted Prismio compiler, AIF, LLVM backend, runtime, and UMS.",
        currentVersion: "0.1.0",
        author: "Saksham Jaiswal",
        authorURL: "https://saksham-1.vercel.app",
        email: "vibrant.official275@gmail.com",
        siteUrl: "https://developers.prismio.org",
        links: {
            github: "https://github.com/prismio-lang/prismio",
            twitter: "",
        },
    },
    brandTag: "Developers",
    accentColor: "purple",
    search: {
        placeholder: "Search compiler internals, AIF, LLVM, UMS…",
        emptyPrompt: "Search versioned implementation pages by title, subsystem, source concept, or diagnostic.",
        categories: {
            start: "Start contributing",
            compiler: "Compiler",
            aif: "AIF and memory",
            llvm: "LLVM",
            runtime: "Runtime",
            tooling: "UMS and tooling",
            testing: "Testing",
            performance: "Performance",
            cookbook: "Cookbook",
            project: "Project reference",
            migration: "Migration",
            releases: "Releases",
        },
    },
    home: {
        badge: {
            versionText: "Prismio 0.1.0",
            tagline: "Compiler-audited developer reference",
        },
        hero: {
            title: "Work on the compiler with the whole system in view.",
            description: "A source-linked reference for Prismio contributors: frontend, semantics, AIF, LLVM, runtime, UMS, testing, performance, and self-hosting.",
            primaryCta: {
                text: "Start reading",
                href: "/start",
            },
            secondaryCta: {
                text: "Read the 0.1.0 baseline",
                href: "/releases/0.1.0",
            },
        },
        statusFacts: [
            { status: "Stable", detail: "Self-hosted compiler, LLVM 22 backend, UMS projects, native tasks, and typed channels" },
            { status: "Experimental", detail: "AIF policy, automatic layout choices, regions, and advanced memory optimization" },
            { status: "Planned", detail: "Async I/O, networking, regex, JSON, user atomics, explicit SIMD, and registry solving" },
        ],
        foundations: {
            sectionLabel: "Learning path",
            title: "From zero to owned data.",
            description: "A short route from checkout to a tested compiler change.",
            items: [
                { href: "/start/local-compiler-loop", label: "Build the local compiler", detail: "Use UMS host routing, staged promotion, and an explicit test generation." },
                { href: "/start/first-compiler-change", label: "Trace one change end to end", detail: "Carry behavior through the frontend, semantics, AIF, LLVM, runtime, tests, and docs." },
            ],
        },
        reference: {
            sectionLabel: "Canonical reference",
            title: "Find the rule, not a guess.",
            items: [
                { href: "/compiler/overview", label: "Compiler internals", detail: "Frontend, semantic analysis, ownership, generics, traits, closures, and lowering." },
                { href: "/aif/overview", label: "AIF and memory", detail: "Allocation tiers, facts, regions, views, layout, reuse, reports, and verification." },
                { href: "/llvm/overview", label: "LLVM backend", detail: "IR types, calls, control flow, the C API bridge, DWARF, and optimization." },
                { href: "/tooling/ums-overview", label: "UMS and tooling", detail: "Manifests, build graphs, compiler promotion, diagnostics, IDEs, and targets." },
            ],
        },
        footer: {
            tagline: "Prismio 0.1.0 implementation reference · Updated 8 Sep 2026",
            links: [
                { href: "/glossary", label: "Glossary" },
                { href: "/faq", label: "FAQ" },
                { href: "/roadmap", label: "Roadmap" },
            ],
        },
    },
    navigation: [
        {
            label: "Start contributing",
            items: [
                { label: "Contributor overview", href: "/start" },
                { label: "Repository tour", href: "/start/repository-tour" },
                { label: "Development environment", href: "/start/development-setup" },
                { label: "Local compiler loop", href: "/start/local-compiler-loop" },
                { label: "First compiler change", href: "/start/first-compiler-change" },
            ],
        },
        {
            label: "Compiler",
            items: [
                { label: "Architecture", href: "/compiler/overview" },
                { label: "Pipeline and driver", href: "/compiler/pipeline-and-driver" },
                { label: "Lexer, parser, and AST", href: "/compiler/frontend" },
                { label: "Imports and symbols", href: "/compiler/imports-and-symbols" },
                { label: "Semantic analysis and types", href: "/compiler/semantic-analysis-and-types" },
                { label: "Ownership and drop lowering", href: "/compiler/ownership-and-drop-lowering" },
                { label: "Generics and monomorphization", href: "/compiler/generics-and-monomorphization" },
                { label: "Traits, impls, and dispatch", href: "/compiler/traits-impls-and-dispatch" },
                { label: "Closures and captures", href: "/compiler/closures-and-captures" },
                { label: "Enums and pattern lowering", href: "/compiler/enums-and-pattern-lowering" },
                { label: "Loop guards", href: "/compiler/loop-guards" },
                { label: "Bootstrapping", href: "/compiler/bootstrap" },
            ],
        },
        {
            label: "AIF and memory",
            items: [
                { label: "AIF overview", href: "/aif/overview" },
                { label: "AIF internals", href: "/compiler/aif-internals" },
                { label: "Tiers and analysis domains", href: "/aif/tiers-and-analysis-domains" },
                { label: "Regions, views, and provenance", href: "/aif/regions-views-and-provenance" },
                { label: "Foreign-function contracts", href: "/aif/ffi-contracts" },
                { label: "Layout selection", href: "/aif/layout-selection" },
                { label: "Reuse, reports, and verification", href: "/aif/reuse-reports-and-verification" },
            ],
        },
        {
            label: "LLVM",
            items: [
                { label: "LLVM backend overview", href: "/llvm/overview" },
                { label: "Types and ABI", href: "/llvm/types-and-abi" },
                { label: "Functions and calls", href: "/llvm/functions-and-calls" },
                { label: "Control-flow lowering", href: "/llvm/control-flow" },
                { label: "LLVM C API bridge", href: "/llvm/llvm-c-bridge" },
                { label: "Debug information", href: "/llvm/debug-information" },
                { label: "Runtime IR and optimization", href: "/llvm/runtime-ir-and-optimization" },
            ],
        },
        {
            label: "Runtime",
            items: [
                { label: "Runtime architecture", href: "/runtime/overview" },
                { label: "String representation", href: "/compiler/string-representation" },
                { label: "Collection representations", href: "/runtime/collection-representations" },
                { label: "Allocation, arenas, RC, and cycles", href: "/runtime/allocation-arenas-rc-and-cycles" },
                { label: "Tasks and channels", href: "/runtime/tasks-and-channels" },
                { label: "Builtins, stdlib, and foreign code", href: "/runtime/supported-surface" },
                { label: "Library artifacts (.bc and .plib)", href: "/runtime/library-artifacts" },
                { label: "Platforms and packaging", href: "/runtime/platform-and-packaging" },
            ],
        },
        {
            label: "UMS and tooling",
            items: [
                { label: "UMS overview", href: "/tooling/ums-overview" },
                { label: "build.ums manifest", href: "/tooling/build-manifest" },
                { label: "Build graph and linking", href: "/tooling/build-graph-and-linking" },
                { label: "Compiler host and promotion", href: "/tooling/compiler-host-and-promotion" },
                { label: "CLI reference", href: "/compiler/cli" },
                { label: "Diagnostics", href: "/compiler/diagnostics" },
                { label: "IDE protocol", href: "/tooling/ide-protocol" },
                { label: "Debugging, targets, and tracing", href: "/tooling/debugging-targets-and-build-tracing" },
            ],
        },
        {
            label: "Testing and performance",
            items: [
                { label: "Testing overview", href: "/testing/overview" },
                { label: "Regression suite", href: "/testing/regression-suite" },
                { label: "Fixed-point verification", href: "/testing/fixed-point-verification" },
                { label: "AIF differential testing", href: "/testing/aif-differential" },
                { label: "Benchmark contract", href: "/performance/benchmark-contract" },
                { label: "Run and extend benchmarks", href: "/performance/running-adding-and-reading-results" },
                { label: "Performance investigations", href: "/performance/investigation-method" },
            ],
        },
        {
            label: "Contributor cookbook",
            items: [
                { label: "Cookbook overview", href: "/cookbook" },
                { label: "C interoperability", href: "/cookbook/c-ffi" },
                { label: "CLI arguments", href: "/cookbook/cli-arguments" },
                { label: "Add a language feature", href: "/cookbook/add-a-language-feature" },
                { label: "Add a diagnostic", href: "/cookbook/add-a-diagnostic" },
                { label: "Add a runtime or stdlib API", href: "/cookbook/add-a-runtime-or-stdlib-api" },
                { label: "Extend UMS", href: "/cookbook/extend-ums" },
                { label: "Debug a regression", href: "/cookbook/debug-a-compiler-regression" },
            ],
        },
        {
            label: "Project reference",
            items: [
                { label: "FAQ", href: "/faq" },
                { label: "Glossary", href: "/glossary" },
                { label: "Migration guides", href: "/migration" },
                { label: "Releases", href: "/releases" },
                { label: "Prismio 0.1.0", href: "/releases/0.1.0" },
                { label: "Engineering roadmap", href: "/roadmap" },
                { label: "Security and compatibility", href: "/project/security-and-compatibility" },
            ],
        },
    ],
};
