import type { editor } from 'monaco-editor';

export const PRISMIO_THEME_DARK = 'prismio-dark';

export const prismioThemeDef: editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: 'keyword', foreground: '818cf8', fontStyle: 'bold' },
        { token: 'keyword.contextual', foreground: 'a5b4fc' },
        { token: 'type.builtin', foreground: '47d7b5', fontStyle: 'bold' },
        { token: 'type.stdlib', foreground: '2dd4bf' },
        { token: 'module.std', foreground: '38bdf8' },
        { token: 'identifier', foreground: 'e4e4e7' },
        { token: 'operator', foreground: '818cf8' },
        { token: 'number', foreground: 'fbbf24' },
        { token: 'number.float', foreground: 'f59e0b' },
        { token: 'number.hex', foreground: 'fcd34d' },
        { token: 'number.binary', foreground: 'fcd34d' },
        { token: 'number.octal', foreground: 'fcd34d' },
        { token: 'string', foreground: '34d399' },
        { token: 'string.quote', foreground: '34d399' },
        { token: 'string.char', foreground: '10b981' },
        { token: 'string.escape', foreground: '6ee7b7', fontStyle: 'bold' },
        { token: 'comment', foreground: '71717a', fontStyle: 'italic' },
        { token: 'delimiter', foreground: '71717a' },
    ],
    colors: {
        'editor.background': '#070709',
        'editor.foreground': '#e4e4e7',
        'editor.lineHighlightBackground': '#0e0f16',
        'editor.lineHighlightBorder': '#00000000',
        'editorLineNumber.foreground': '#52525b',
        'editorLineNumber.activeForeground': '#47d7b5',
        'editorCursor.foreground': '#47d7b5',
        'editor.selectionBackground': '#47d7b533',
        'editor.inactiveSelectionBackground': '#47d7b51a',
        'editorWhitespace.foreground': '#27272a',
        'editorIndentGuide.background1': '#18181b',
        'editorIndentGuide.activeBackground1': '#27272a',
        'editorBracketMatch.background': '#47d7b522',
        'editorBracketMatch.border': '#47d7b555',
        'editorWidget.background': '#0c0d12',
        'editorWidget.border': '#27272a',
        'editorSuggestWidget.background': '#0c0d12',
        'editorSuggestWidget.border': '#27272a',
        'editorSuggestWidget.foreground': '#e4e4e7',
        'editorSuggestWidget.selectedBackground': '#18181b',
        'editorSuggestWidget.highlightForeground': '#47d7b5',
        'editorHoverWidget.background': '#0c0d12',
        'editorHoverWidget.border': '#27272a',
        'scrollbarSlider.background': '#ffffff14',
        'scrollbarSlider.hoverBackground': '#ffffff24',
        'scrollbarSlider.activeBackground': '#ffffff3a',
    },
};
